<a href="https://colab.research.google.com/github/Caosbot/Treinos_Python/blob/Data_Science/Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inicio

### Contem os camandos para subir do local para o colab

In [118]:
#from google.colab import files
#upload = files.upload()

## Import e data

In [119]:
import pandas as pd
import numpy as np

In [120]:
df = pd.read_csv(r"F:\Cursos\DNC\Banco de dados\DataPrepFinal.csv")
df

,Unnamed: 0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,09/10/15,100000,11/08/15 12:12,0,failed,0,GB,0.0,0,USD 153395
1,1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,01/11/17,3000000,02/09/17 04:43,242100,failed,15,US,10000.0,242100,USD 3000000
2,2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,26/02/13,4500000,12/01/13 00:20,22000,failed,3,US,22000.0,22000,USD 4500000
3,3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,16/04/12,500000,17/03/12 03:24,100,failed,1,US,100.0,100,USD 500000
4,4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,29/08/15,1950000,04/07/15 08:35,128300,canceled,14,US,128300.0,128300,USD 1950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19458,19458,1098725026,Keeping Photography an Art,People,Photography,USD,25/09/15,1000000,27/07/15 20:17,0,failed,0,US,0.0,0,USD 1000000
19459,19459,1098726927,Christmas Village coloring/story book.,Children's Books,Publishing,USD,07/11/14,550000,06/10/14 20:45,6400,failed,7,US,6400.0,6400,USD 550000
19460,19460,1098729640,Co-Create a Mantra CD to Elevate the Spirit!,World Music,Music,USD,30/04/11,727500,31/03/11 18:22,80000,failed,21,US,80000.0,80000,USD 727500
19461,19461,10987305,By Our Rules (Working Title),Documentary,Film & Video,USD,17/06/14,1000000,18/04/14 22:36,22000,failed,6,US,22000.0,22000,USD 1000000
19462,19462,1098735707,Quad Lock - iPhone Case Mounting System,Product Design,Design,USD,15/01/12,2000000,05/12/11 09:29,4120943,successful,666,US,4120943.0,4120943,USD 2000000

In [121]:
df.columns

Index(['Unnamed: 0', 'ID', 'name', 'category', 'main_category', 'currency',
       'deadline', 'goal', 'launched', 'pledged', 'state', 'backers',
       'country', 'usd pledged', 'usd_pledged_real', 'usd_goal_real'],
      dtype='object')

## Manipulação dos dados

In [122]:
df = df.drop(columns=['Unnamed: 0','name', 'category','goal','pledged','usd pledged'])
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,USD 153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,USD 3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,USD 4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,USD 500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,USD 1950000

In [123]:
df.dtypes

ID                   int64
main_category       object
currency            object
deadline            object
launched            object
state               object
backers              int64
country             object
usd_pledged_real     int64
usd_goal_real       object
dtype: object

In [124]:
#df['usd_goal_real']= df['usd_goal_real'].str.replace("USD ", "")
df['usd_goal_real'].apply(lambda x: x.strip("USD ")) #Caso não haja uma função existente, aqui se cria a função para a troca

0         153395
1        3000000
2        4500000
3         500000
4        1950000
          ...
19458    1000000
19459     550000
19460     727500
19461    1000000
19462    2000000
Name: usd_goal_real, Length: 19463, dtype: object

In [125]:
df['usd_goal_real'] = df['usd_goal_real'].apply(lambda x: x.strip("USD ")) #Aqui é a aplicação no dataframe
df['usd_goal_real'] = df['usd_goal_real'].astype('int64') #Mudando de string para inteiro

In [126]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,1950000

In [127]:
df['launched'].str.replace(" \d\d:\d\d","",regex=True)#Usando RegEx \d representa um numero

0        11/08/15
1        02/09/17
2        12/01/13
3        17/03/12
4        04/07/15
           ...
19458    27/07/15
19459    06/10/14
19460    31/03/11
19461    18/04/14
19462    05/12/11
Name: launched, Length: 19463, dtype: object

In [128]:
df['launched']= df['launched'].str.replace(" \d\d:\d\d","",regex=True)

In [129]:
df['launched']= pd.to_datetime(df['launched'], format='%d/%m/%y')
df['deadline']= pd.to_datetime(df['deadline'], format='%d/%m/%y')

In [130]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000

In [131]:
df.dtypes

ID                           int64
main_category               object
currency                    object
deadline            datetime64[ns]
launched            datetime64[ns]
state                       object
backers                      int64
country                     object
usd_pledged_real             int64
usd_goal_real                int64
dtype: object

In [132]:
(df["deadline"]-df["launched"]).dt.days #dt.days apenas retira a palavra days depois do numero

0        59
1        60
2        45
3        30
4        56
         ..
19458    60
19459    32
19460    30
19461    60
19462    41
Length: 19463, dtype: int64

In [133]:
df["time_range"] = (df["deadline"]-df["launched"]).dt.days
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56

## Novos dataframes

### Campanha

In [134]:
df_c = pd.read_csv(r"F:\Cursos\DNC\Banco de dados\campaign.csv")
df_c

               ID  Text Description  Video  Image  Infographic  Reviews  Risks
0      1000002330                 1      1      1            1        0      1
1      1000003930                 1      1      1            1        1      0
2      1000004038                 1      0      1            1        0      1
3      1000007540                 1      1      0            1        0      0
4      1000011046                 1      0      1            0        0      0
...           ...               ...    ...    ...          ...      ...    ...
19458  1098725026                 1      0      0            0        0      1
19459  1098726927                 1      1      0            1        0      0
19460  1098729640                 1      1      1            1        1      1
19461    10987305                 1      1      0            0        0      0
19462  1098735707                 1      0      1            1        1      1

[19463 rows x 7 columns]

In [135]:
df_c['Text Description'].unique()

array([1], dtype=int64)

In [136]:
df_c = df_c.drop(columns=['Text Description'])
df_c.head()

           ID  Video  Image  Infographic  Reviews  Risks
0  1000002330      1      1            1        0      1
1  1000003930      1      1            1        1      0
2  1000004038      0      1            1        0      1
3  1000007540      1      0            1        0      0
4  1000011046      0      1            0        0      0

In [137]:
df.merge(df_c, how='right', on=["ID"])

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59,1,1,1,0,1
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60,1,1,1,1,0
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45,0,1,1,0,1
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30,1,0,1,0,0
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19458,1098725026,Photography,USD,2015-09-25,2015-07-27,failed,0,US,0,1000000,60,0,0,0,0,1
19459,1098726927,Publishing,USD,2014-11-07,2014-10-06,failed,7,US,6400,550000,32,1,0,1,0,0
19460,1098729640,Music,USD,2011-04-30,2011-03-31,failed,21,US,80000,727500,30,1,1,1,1,1
19461,10987305,Film & Video,USD,2014-06-17,2014-04-18,failed,6,US,22000,1000000,60,1,0,0,0,0
19462,1098735707,Design,USD,2012-01-15,2011-12-05,successful,666,US,4120943,2000000,41,0,1,1,1,1

In [138]:
df = df.merge(df_c, how='right', on=["ID"])

### Invested

In [139]:
df_i = pd.read_csv(r"F:\Cursos\DNC\Banco de dados\invested.csv")
df_i

               ID backedLocation  age
0      1000003930             BR   18
1      1000004038             US   57
2      1000007540             US   43
3      1000011046             BR   29
4      1000014025             BR   77
...           ...            ...  ...
35391  1098718520             US   68
35392  1098726927             BR   30
35393  1098729640             US   20
35394    10987305             BR   19
35395  1098735707             US   63

[35396 rows x 3 columns]

In [140]:
df_i.sort_values(by=["ID"])

               ID backedLocation  age
27400      106144             US   63
10585      106144            GBK   70
17409     1003381             BR   68
594       1003381             US   29
2925      1017454             US   62
...           ...            ...  ...
16812  1098729640            GBK   61
33627  1098729640            GBK   43
16814  1098735707             BR   66
33629  1098735707             US   62
35395  1098735707             US   63

[35396 rows x 3 columns]

### Aplicando One-Hot

In [141]:
df_i['backedLocation'].unique()

array(['BR', 'US', 'GBK'], dtype=object)

In [142]:
pd.get_dummies(df_i,columns=['backedLocation'])

,ID,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
0,1000003930,18,True,False,False
1,1000004038,57,False,False,True
2,1000007540,43,False,False,True
3,1000011046,29,True,False,False
4,1000014025,77,True,False,False
...,...,...,...,...,...
35391,1098718520,68,False,False,True
35392,1098726927,30,True,False,False
35393,1098729640,20,False,False,True
35394,10987305,19,True,False,False
35395,1098735707,63,False,False,True

In [143]:
df_i = pd.get_dummies(df_i,columns=['backedLocation'])
df_i.head()

           ID  age  backedLocation_BR  backedLocation_GBK  backedLocation_US
0  1000003930   18               True               False              False
1  1000004038   57              False               False               True
2  1000007540   43              False               False               True
3  1000011046   29               True               False              False
4  1000014025   77               True               False              False

In [144]:
df_i['ID'].sort_values()

27400        106144
10585        106144
17409       1003381
594         1003381
2925        1017454
            ...
16812    1098729640
33627    1098729640
16814    1098735707
33629    1098735707
35395    1098735707
Name: ID, Length: 35396, dtype: int64

In [148]:
df_i.sort_values(by=["ID"])

,ID,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
27400,106144,63,False,False,True
10585,106144,70,False,True,False
17409,1003381,68,True,False,False
594,1003381,29,False,False,True
2925,1017454,62,False,False,True
...,...,...,...,...,...
16812,1098729640,61,False,True,False
33627,1098729640,43,False,True,False
16814,1098735707,66,True,False,False
33629,1098735707,62,False,False,True
35395,1098735707,63,False,False,True

In [156]:
df_i.groupby(by=["ID"]).agg({"age": lambda x: round(x.mean(),2), "backedLocation_BR": "sum", "backedLocation_GBK":"sum",  "backedLocation_US":"sum"})

              age  backedLocation_BR  backedLocation_GBK  backedLocation_US
ID
106144      66.50                  0                   1                  1
1003381     48.50                  1                   0                  1
1017454     41.50                  0                   0                  2
1024013     77.00                  2                   0                  0
1024208     71.00                  0                   1                  1
...           ...                ...                 ...                ...
1098710911  31.00                  2                   0                  1
1098718520  39.33                  0                   2                  1
1098726927  38.00                  1                   0                  2
1098729640  41.33                  0                   2                  1
1098735707  63.67                  1                   0                  2

[16815 rows x 4 columns]

In [157]:
df_i = df_i.groupby(by=["ID"]).agg({"age": lambda x: round(x.mean(),2), "backedLocation_BR": "sum", "backedLocation_GBK":"sum",  "backedLocation_US":"sum"})

In [158]:
df.merge(df_i, how="right", on=(["ID"]))

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
0,106144,Music,USD,2014-06-15,2014-05-16,failed,1,US,1500,180000,30,1,1,0,0,1,66.50,0,1,1
1,1003381,Music,USD,2012-07-19,2012-06-21,failed,30,US,115900,1000000,28,0,1,0,1,1,48.50,1,0,1
2,1017454,Film & Video,USD,2015-04-26,2015-04-20,successful,9,US,16700,100,6,1,0,1,0,1,41.50,0,0,2
3,1024013,Publishing,USD,2012-05-18,2012-04-03,failed,136,US,975805,4000000,45,1,1,1,0,0,77.00,2,0,0
4,1024208,Technology,USD,2014-09-11,2014-08-12,failed,5,US,15000,150000,30,0,1,1,0,0,71.00,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16810,1098710911,Film & Video,USD,2014-11-06,2014-10-07,failed,26,US,187100,555000,30,1,0,1,1,1,31.00,2,0,1
16811,1098718520,Film & Video,USD,2014-10-01,2014-08-30,failed,2,US,3500,550000,32,1,0,0,0,0,39.33,0,2,1
16812,1098726927,Publishing,USD,2014-11-07,2014-10-06,failed,7,US,6400,550000,32,1,0,1,0,0,38.00,1,0,2
16813,1098729640,Music,USD,2011-04-30,2011-03-31,failed,21,US,80000,727500,30,1,1,1,1,1,41.33,0,2,1
16814,1098735707,Design,USD,2012-01-15,2011-12-05,successful,666,US,4120943,2000000,41,0,1,1,1,1,63.67,1,0,2

In [159]:
df = df.merge(df_i, how="right", on=("ID"))

In [160]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
0,106144,Music,USD,2014-06-15,2014-05-16,failed,1,US,1500,180000,30,1,1,0,0,1,66.5,0,1,1
1,1003381,Music,USD,2012-07-19,2012-06-21,failed,30,US,115900,1000000,28,0,1,0,1,1,48.5,1,0,1
2,1017454,Film & Video,USD,2015-04-26,2015-04-20,successful,9,US,16700,100,6,1,0,1,0,1,41.5,0,0,2
3,1024013,Publishing,USD,2012-05-18,2012-04-03,failed,136,US,975805,4000000,45,1,1,1,0,0,77.0,2,0,0
4,1024208,Technology,USD,2014-09-11,2014-08-12,failed,5,US,15000,150000,30,0,1,1,0,0,71.0,0,1,1